name: Update References

on:
  push:
    branches: [ main ]
    paths:
    - '**.py'
  schedule:
    - cron: '41 6 * * *'
  workflow_dispatch: null

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: 'true'
    - name: Update RFCs
      run: make update
    - name: Create refs.json
      run: make refs.json
    - name: Upload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bash -x ./upload.sh
